name: Weather Report

on:
  schedule:
    - cron: '0 9 * * *'

jobs:

  extract_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Get weather data
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        import urllib.request
        import json
        from datetime import datetime
        import os
        import git

        def get_weather_data(city):
            url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={os.environ['OPENWEATHER_API_KEY']}&units=metric"
            with urllib.request.urlopen(url) as response:
                data = json.load(response)
            return {
                "city": city,
                "temperature": data["main"]["temp"],
                "description": data["weather"][0]["description"]
            }

        cities = ["Minsk", "Paris", "Munich"]
        weather_data = [get_weather_data(city) for city in cities]

        weather_report = "\n".join([f"{data['city']}: {data['temperature']}°C, {data['description']}" for data in weather_data])

        current_date = datetime.now().strftime("%Y-%m-%d")
        file_name = f"weather_report_{current_date}.txt"

        if not os.path.exists(".git"):
            repo = git.Repo.init(".")
        else:
            repo = git.Repo(".")

        with open(file_name, "w") as f:
            f.write(weather_report)
        repo.git.add(file_name)
        repo.index.commit(f"Add weather report for {current_date}")
        origin = repo.remote(name='origin')
        origin.push()

        print(f"Weather report saved to {file_name} and uploaded to GitHub.")

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Add weather report'
